### ISSUE TITLE
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again

### ISSUE THREAD

**Issue by sydneyitguy** [hosopy/actioncable-client-java#3]
Thanks for open-sourcing this library. I'm using this in one of my projects,
and I recently found a crash from `com.hosopy.actioncable.ConnectionMonitor.poll` method

```
  java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
      at java.lang.Thread.nativeCreate(Native Method)
      at java.lang.Thread.start(Thread.java:1063)
      at java.util.Timer$TimerImpl.<init>(Timer.java:192)
      at java.util.Timer.<init>(Timer.java:365)
      at java.util.Timer.<init>(Timer.java:384)
      at java.util.Timer.<init>(Timer.java:391)
      at com.hosopy.actioncable.ConnectionMonitor.poll(ConnectionMonitor.java:69)
      at com.hosopy.actioncable.ConnectionMonitor.access$200(ConnectionMonitor.java:6)
      at com.hosopy.actioncable.ConnectionMonitor$1.run(ConnectionMonitor.java:75)
      at java.util.Timer$TimerImpl.run(Timer.java:284)
```

I found a relevant issue here http://stackoverflow.com/questions/35701501/throwing-outofmemoryerror-pthread-create-1040kb-stack-failed-try-again-when

I guess it's probably because the timer variable is created repeatedly on
https://github.com/hosopy/actioncable-client-java/blob/master/src/main/java/com/hosopy/actioncable/ConnectionMonitor.java#L69
but I haven't tested the fix.

It is hard to reproduce the issue because it only happens after the app's running for a long time.
Do you think making the timer variable to an instance variable would fix the issue?

**Comment by tz-xiaomage** [comment]
@sydneyitguy hello，What is your solution
