### ISSUE TITLE
Crash on Android 

### ISSUE THREAD

**Issue by albka1986** [hosopy/actioncable-client-java#30]
10-02 18:37:26.946 3708-4058/com.company E/AndroidRuntime: FATAL EXCEPTION: EventLoop
    Process: com.company, PID: 3708
    java.lang.IllegalStateException: closed
        at com.squareup.okhttp.internal.ws.RealWebSocket.sendMessage(RealWebSocket.java:109)
        at com.hosopy.actioncable.Connection.doSend(Connection.java:221)
        at com.hosopy.actioncable.Connection.access$500(Connection.java:22)
        at com.hosopy.actioncable.Connection$3.run(Connection.java:165)
        at com.hosopy.concurrent.EventLoop$2.run(EventLoop.java:69)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by h0jeZvgoxFepBQ2C** [comment]
Would be great if you could test out if this happens also with the [latest RC](https://github.com/hosopy/actioncable-client-java/releases/tag/0.2.RC1).
Or can this issue be closed?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Stale. Please submit a new ticket if this is still open.
